name: build-package

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-ui:
    name: Build Package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install
        run: |
          pnpm install --frozen-lockfile

      - name: Build
        run: |
          pnpm build
          npm pack

      - name: Create Release
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            i18n-toolkit*.tgz
